gastos = float(input("Cuanto gastaron los gachis? "))
gachi = float(gastos * 0.57)
tachi = float(gastos * 0.43)
print ("Los gastos segun el sueldo serian:")
print ("El gachi tiene que poner:")
print (f"{gachi:.2f}")
print ("La tachita tiene que poner:")
print (f"{tachi:.2f}")